### ISSUE TITLE
Failures just with Android 5.1 (SDK 22), audioplayers 0.18.2

### ISSUE THREAD

**Issue by thize** [luanpotter/audioplayers#829]
My app started to have failures ONLY on Android 5.1 (SDK 22) after I updated the plugin to 0.18.2

Before version 0.18.2 I used version 0.18.0, so I can't say that it doesn't happen in 0.18.1 too.

Kotlin Version:
ext.kotlin_version = '1.4.31'

**Log Errors**

java.lang.NoClassDefFoundError: 
  at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl (WrappedMediaPlayer.kt:42)
  at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall (AudioplayersPlugin.kt:59)
  at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall (AudioplayersPlugin.kt:34)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:233)
  at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart (DartMessenger.java:85)
  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage (FlutterJNI.java:818)
  at android.os.MessageQueue.nativePollOnce (Native Method)
  at android.os.MessageQueue.next (MessageQueue.java:143)
  at android.os.Looper.loop (Looper.java:130)
  at android.app.ActivityThread.main (ActivityThread.java:6946)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:511)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:469)

**Screenshots**
Devices:
![image](https://user-images.githubusercontent.com/10541221/113271700-2d313b80-92b1-11eb-8a1e-3aa6c2845d6a.png)

Android Version:
![image](https://user-images.githubusercontent.com/10541221/113273861-6ff41300-92b3-11eb-8b86-738ec92d1338.png)

**Comment by pbouttier** [comment]
Same thing in Android 5.0

**Comment by erickzanardo** [comment]
Not all features works on all platforms, can you check if the feature that you are using is supported on that level of Android? You can check on our parity table [here](https://github.com/luanpotter/audioplayers/blob/master/feature_parity_table.md)

The reason that you didn't saw this on 0.18.0, was probably because using below 23 couldn't install your app as we had a constraint on Audioplayers as seen [here](https://github.com/luanpotter/audioplayers/blob/0.18.0/android/build.gradle#L35).

**Comment by husen-hn** [comment]
The same thing with Android 5.0 with this error but it does not matter what version I used: 

```dart
E/AndroidRuntime(29426): FATAL EXCEPTION: main
E/AndroidRuntime(29426): Process: com.example.feedTest, PID: 29426
E/AndroidRuntime(29426): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/media/MediaDataSource;
E/AndroidRuntime(29426): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:42)
E/AndroidRuntime(29426): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/AndroidRuntime(29426): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:34)
E/AndroidRuntime(29426): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(29426): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(29426): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(29426): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(29426): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/AndroidRuntime(29426): 	at android.os.Looper.loop(Looper.java:122)
E/AndroidRuntime(29426): 	at android.app.ActivityThread.main(ActivityThread.java:5264)
E/AndroidRuntime(29426): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29426): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(29426): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
E/AndroidRuntime(29426): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
E/AndroidRuntime(29426): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.media.MediaDataSource" on path: DexPathList[[zip file "/data/app/com.example.feedTest-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.feedTest-2/lib/x86, /vendor/lib, /system/lib]]
E/AndroidRuntime(29426): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(29426): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(29426): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(29426): 	... 14 more
E/AndroidRuntime(29426): 	Suppressed: java.lang.ClassNotFoundException: android.media.MediaDataSource
E/AndroidRuntime(29426): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(29426): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(29426): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(29426): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(29426): 		... 15 more
E/AndroidRuntime(29426): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available```

**Comment by luanpotter** [comment]
I think the code we use at `t xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:42)` must not be working with older SDK versions, so we might need to add the version check `if` like I said @erickzanardo

**Comment by erickzanardo** [comment]
That seems about right @luanpotter , apparently MediaSource was added on API 23: https://developer.android.com/reference/android/media/MediaDataSource

Do you know if there is an alternative to that class?

**Comment by luanpotter** [comment]
probably we won't support some very specific feature (respect silence, duck audio, something new that was added). but definitely there was a way we did it back in ancient times
