### ISSUE TITLE
Can no longer build for iOS since upgrade to iOS 13.x

### ISSUE THREAD

**Issue by sallymariehollywood** [luanpotter/audioplayers#289]
Hi - This plugin used to work perfectly but since upgrading Flutter to 1.9.1 hotfix 4 and iOS 13.1.2
I can not longer build my app for iOS **on a live device.** When I change the build to **legacy** I get the following error 
```

=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Target 'Pods-Runner' of project 'Pods' was rejected as an implicit dependency for 'Pods_Runner.framework' because its architectures
    'arm64' didn't contain all required architectures 'armv7 arm64'
    GeneratedPluginRegistrant.m:6:9: fatal error:
    'audioplayers/AudioplayersPlugin.h' file not found
    #import <audioplayers/AudioplayersPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    GeneratedPluginRegistrant.m:6:9: fatal error:
    'audioplayers/AudioplayersPlugin.h' file not found
    #import <audioplayers/AudioplayersPlugin.h>
```

When I use the **new build** I get :
```

 GeneratedPluginRegistrant.m:6:9: fatal error:
    'audioplayers/AudioplayersPlugin.h' file not found
    #import <audioplayers/AudioplayersPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
 GeneratedPluginRegistrant.m:6:9: fatal error:
    'audioplayers/AudioplayersPlugin.h' file not found
    #import <audioplayers/AudioplayersPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description
```
I can run my app on **a simulator**  without any issue. The issue only occurs when I try  and build and deploy the app in terminal with VS CODE, i.e issuing the command 

 **flutter run -d 'device id'**

Its weird that the app appears to run on a simulator but not on a live device. Additionally - if the project is opened via XCODE - **I can build and  deploy on a live device**

**Comment by mhd-barikhan** [comment]
change build settings to legacy in xcode

**Comment by luanpotter** [comment]
@erickzanardo can you make sure the current version is working on a live device? I only tested on the simulator

**Comment by erickzanardo** [comment]
@luanpotter this issue is about iOS 13 and has one year already. We are at iOS 14 already and I have some of our own games installed that uses audioplayers. I think it is safe to close.
