### PR TITLE
Fixing basic features for Android lower than API 23

### LINKED ISSUE #829: Failures just with Android 5.1 (SDK 22), audioplayers 0.18.2
My app started to have failures ONLY on Android 5.1 (SDK 22) after I updated the plugin to 0.18.2

Before version 0.18.2 I used version 0.18.0, so I can't say that it doesn't happen in 0.18.1 too.

Kotlin Version:
ext.kotlin_version = '1.4.31'

**Log Errors**

java.lang.NoClassDefFoundError: 
  at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl (WrappedMediaPlayer.kt:42)
  at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall (AudioplayersPlugin.kt:59)
  at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall (AudioplayersPlugin.kt:34)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:233)
  at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart (DartMessenger.java:85)
  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage (FlutterJNI.java:818)
  at android.os.MessageQueue.nativePollOnce (Native Method)
  at android.os.MessageQueue.next (MessageQueue.java:143)
  at android.os.Looper.loop (Looper.java:130)
  at android.app.ActivityThread.main (ActivityThread.java:6946)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:511)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:469)

**Screenshots**
Devices:
image

Android Version:
image

### PR DESCRIPTION
**Pull request by erickzanardo**
This PR re-enables the basic features of AudioPlayers on devices older than API 23

Fixes #829

### CODE REVIEW

File: android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt [hunk 1]
```diff
@@ -38,16 +38,20 @@ class WrappedMediaPlayer internal constructor(
...
-            player.setDataSource(mediaDataSource)
-            preparePlayer(player)
+        if (Build.VERSION.SDK_INT >= 23) {
+            if (!objectEquals(dataSource, mediaDataSource)) {
+                dataSource = mediaDataSource
+                val player = getOrCreatePlayer()
+                player.setDataSource(mediaDataSource)
+                preparePlayer(player)
+            }
         }
```
Comment (luanpotter) [inline android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt:55]: probably should throw if called on other platforms? to make sure the callee checks `if (Build.VERSION.SDK_INT >= 23` and calls something else insetad?

File: android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt [hunk 2]
```diff
@@ -109,7 +113,9 @@ class WrappedMediaPlayer internal constructor(
         this.rate = rate.toFloat()
 
         val player = this.player ?: return
-        player.playbackParams = player.playbackParams.setSpeed(this.rate)
+        if (Build.VERSION.SDK_INT >= 23) {
+            player.playbackParams = player.playbackParams.setSpeed(this.rate)
+        }
```
Comment (luanpotter) [inline android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt:118]: should we log a warning on old platforms?

**Review by luanpotter — APPROVED** [review]
LGTM, make sure to add `@Suppress("DEPRECATION")` to any deprecated method and comment that it's only used on obsolete platforms

File: android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt (hunk 1 above)
Comment (erickzanardo) [reply android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt:55]: Sounds good, any standard you are using for throwing exceptions in the project that I should follow?

File: android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt (hunk 2 above)
Comment (erickzanardo) [reply android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt:118]: Not sure if it is necessary, I have updated the parity table marking this feature as >= 23 only. But if you want to add a log here lmk and I can add

File: android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt (hunk 1 above)
Comment (luanpotter) [reply android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt:55]: no preference, you can use check/require (https://www.bignerdranch.com/blog/write-better-code-using-kotlins-require-check-and-assert/) or just throw RuntimeException with message

File: android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt (hunk 2 above)
Comment (luanpotter) [reply android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt:118]: I think I prefer it personally but we should be consistent everywhere, so if it's not logged on other methods we can leave and decide on another PR
